package com.test.jfinal;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.test.domain.Authrecord;
import com.test.domain.Customer;
import com.test.domain.Hotel;
import com.test.domain.Logininfo;
import com.test.domain.Manager;
import com.test.domain.Systemdic;
import com.test.domain.Systemdicitem;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("authrecord", "id", Authrecord.class);
		arp.addMapping("customer", "id", Customer.class);
		arp.addMapping("hotel", "id", Hotel.class);
		arp.addMapping("logininfo", "id", Logininfo.class);
		arp.addMapping("manager", "id", Manager.class);
		arp.addMapping("systemdic", "id", Systemdic.class);
		arp.addMapping("systemdicitem", "id", Systemdicitem.class);
	}
}

