package com.test.domain;

import com.test.domain.base.BaseSystemdicitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Systemdicitem extends BaseSystemdicitem<Systemdicitem> {
}
