package com.test.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHotel<M extends BaseHotel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setHotelName(java.lang.String hotelName) {
		set("hotelName", hotelName);
	}

	public java.lang.String getHotelName() {
		return get("hotelName");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setClientSn(java.lang.String clientSn) {
		set("clientSn", clientSn);
	}

	public java.lang.String getClientSn() {
		return get("clientSn");
	}

	public void setRegionofprovinceId(java.lang.Long regionofprovinceId) {
		set("regionOfProvince_id", regionofprovinceId);
	}

	public java.lang.Long getRegionofprovinceId() {
		return get("regionOfProvince_id");
	}

	public void setRegionofcityId(java.lang.Long regionofcityId) {
		set("regionOfCity_id", regionofcityId);
	}

	public java.lang.Long getRegionofcityId() {
		return get("regionOfCity_id");
	}

	public void setRegionofareaId(java.lang.Long regionofareaId) {
		set("regionOfArea_id", regionofareaId);
	}

	public java.lang.Long getRegionofareaId() {
		return get("regionOfArea_id");
	}

}
