package com.test.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManager<M extends BaseManager<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setRealName(java.lang.String realName) {
		set("realName", realName);
	}

	public java.lang.String getRealName() {
		return get("realName");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return get("sn");
	}

	public void setRegionofprovinceId(java.lang.Long regionofprovinceId) {
		set("regionOfProvince_id", regionofprovinceId);
	}

	public java.lang.Long getRegionofprovinceId() {
		return get("regionOfProvince_id");
	}

	public void setRegionofcityId(java.lang.Long regionofcityId) {
		set("regionOfCity_id", regionofcityId);
	}

	public java.lang.Long getRegionofcityId() {
		return get("regionOfCity_id");
	}

	public void setRegionofareaId(java.lang.Long regionofareaId) {
		set("regionOfArea_id", regionofareaId);
	}

	public java.lang.Long getRegionofareaId() {
		return get("regionOfArea_id");
	}

}
