package com.test.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuthrecord<M extends BaseAuthrecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setResult(java.lang.Float result) {
		set("result", result);
	}

	public java.lang.Float getResult() {
		return get("result");
	}

	public void setAuthTime(java.util.Date authTime) {
		set("authTime", authTime);
	}

	public java.util.Date getAuthTime() {
		return get("authTime");
	}

	public void setAuthorId(java.lang.Long authorId) {
		set("author_id", authorId);
	}

	public java.lang.Long getAuthorId() {
		return get("author_id");
	}

	public void setAuthorhotelId(java.lang.Long authorhotelId) {
		set("authorHotel_id", authorhotelId);
	}

	public java.lang.Long getAuthorhotelId() {
		return get("authorHotel_id");
	}

}
